version: '3.7'
services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports: 
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=jadiganteng
      - CASC_JENKINS_CONFIG=/usr/local/configuration/casc.yaml
    volumes: 
      - ./data/drive/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - ./configuration:/usr/local/configuration